import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "../src/server.js";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

async function fixture() {
  const server=createServer().listen(0);await new Promise(resolve=>server.once("listening",resolve));
  const base=`http://127.0.0.1:${server.address().port}`;
  const response=await fetch(`${base}/api/v1/auth/register`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:`dev-${crypto.randomUUID()}@example.com`,displayName:"Test Developer"})});
  const account=await response.json(); return {server,base,token:account.token,headers:{"content-type":"application/json",authorization:`Bearer ${account.token}`}};
}
const manifest=(id="com.example.valid")=>({schemaVersion:1,id,name:"Valid",version:"1.0.0",rtools:{minVersion:"0.5.0"},entry:{type:"declarative"},commands:[],permissions:[]});
const upload=value=>({manifest:value,packageSha256:"0".repeat(64),packageSize:100,fileManifest:[]});

test("serves shared protocol",async()=>{const {server,base}=await fixture();const response=await fetch(`${base}/api/v1/protocol/schema`);assert.equal(response.status,200);assert.equal((await response.json()).title,"RTools Plugin Manifest v1");server.close();});
test("serves the admin console",async()=>{const {server,base}=await fixture();const response=await fetch(`${base}/admin`);assert.equal(response.status,200);assert.match(await response.text(),/RTools Marketplace 管理后台/);server.close();});
test("creates an expiring administrator session",async()=>{const {server,base}=await fixture();let response=await fetch(`${base}/api/v1/admin/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:"admin",password:"test-admin"})});assert.equal(response.status,200);const {token}=await response.json();response=await fetch(`${base}/api/v1/admin/audit`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,200);server.close();});
test("requires authentication",async()=>{const {server,base}=await fixture();const response=await fetch(`${base}/api/v1/developer/plugins`);assert.equal(response.status,401);assert.equal((await response.json()).code,"AUTH_REQUIRED");server.close();});
test("manages individual developer API tokens",async()=>{const {server,base,headers}=await fixture();let response=await fetch(`${base}/api/v1/developer/tokens`,{method:"POST",headers,body:JSON.stringify({name:"CI"})});assert.equal(response.status,201);const created=await response.json();assert.match(created.token,/^rtm_/);response=await fetch(`${base}/api/v1/developer/tokens`,{headers});assert.equal((await response.json()).items.length,2);response=await fetch(`${base}/api/v1/developer/tokens/${created.id}`,{method:"DELETE",headers});assert.equal((await response.json()).revoked,true);server.close();});
test("suspends developers and revokes API tokens",async()=>{const {server,base,token}=await fixture(),admin={"content-type":"application/json",authorization:"Bearer test-admin-token"};let response=await fetch(`${base}/api/v1/admin/developers`,{headers:admin}),developers=(await response.json()).items,developer=developers[0];assert.equal(developer.activeTokenCount,1);response=await fetch(`${base}/api/v1/admin/developers/${developer.id}/status`,{method:"POST",headers:admin,body:JSON.stringify({status:"suspended"})});assert.equal((await response.json()).status,"suspended");response=await fetch(`${base}/api/v1/developer/plugins`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,401);await fetch(`${base}/api/v1/admin/developers/${developer.id}/status`,{method:"POST",headers:admin,body:JSON.stringify({status:"active"})});response=await fetch(`${base}/api/v1/admin/developers/${developer.id}/revoke-tokens`,{method:"POST",headers:admin});assert.equal((await response.json()).revoked,1);response=await fetch(`${base}/api/v1/developer/plugins`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,401);server.close();});
test("rejects unknown permission during preflight",async()=>{const {server,base,headers}=await fixture();const invalid=manifest("com.example.invalid");invalid.permissions=["filesystem:all"];const response=await fetch(`${base}/api/v1/developer/plugins/${invalid.id}/versions/preflight`,{method:"POST",headers,body:JSON.stringify(upload(invalid))});assert.equal(response.status,422);assert.equal((await response.json()).code,"PLUGIN_PERMISSION_UNKNOWN");server.close();});
test("creates plugin and submits immutable version",async()=>{const {server,base,headers}=await fixture(),value=manifest();let response=await fetch(`${base}/api/v1/developer/plugins/${value.id}/versions`,{method:"POST",headers,body:JSON.stringify(upload(value))});assert.equal(response.status,201);assert.equal((await response.json()).status,"pending_review");response=await fetch(`${base}/api/v1/developer/plugins/${value.id}/versions`,{method:"POST",headers,body:JSON.stringify(upload(value))});assert.equal(response.status,409);assert.equal((await response.json()).code,"PLUGIN_VERSION_EXISTS");response=await fetch(`${base}/api/v1/developer/plugins`,{headers});assert.equal((await response.json()).items[0].versions.length,1);server.close();});
test("reviews, publishes and unpublishes a scanned version",async()=>{const {server,base,headers}=await fixture(),value=manifest(`com.example.review-${crypto.randomUUID()}`);let response=await fetch(`${base}/api/v1/developer/plugins/${value.id}/versions`,{method:"POST",headers,body:JSON.stringify(upload(value))});const version=await response.json();const admin={"content-type":"application/json",authorization:"Bearer test-admin-token"};response=await fetch(`${base}/api/v1/admin/versions/${version.id}/review`,{method:"POST",headers:admin,body:JSON.stringify({decision:"approved",note:"Reviewed"})});assert.equal((await response.json()).status,"approved");response=await fetch(`${base}/api/v1/admin/versions/${version.id}/publish`,{method:"POST",headers:admin});assert.equal((await response.json()).status,"published");response=await fetch(`${base}/api/v1/plugins`);assert.equal((await response.json()).items.length,1);response=await fetch(`${base}/api/v1/admin/versions/${version.id}/unpublish`,{method:"POST",headers:admin});assert.equal((await response.json()).status,"unpublished");response=await fetch(`${base}/api/v1/plugins`);assert.equal((await response.json()).items.length,0);server.close();});
test("checks compatibility range",async()=>{const {server,base}=await fixture();const response=await fetch(`${base}/api/v1/compatibility?hostVersion=0.6.0&minVersion=0.5.0&maxVersion=0.7.0`);assert.equal((await response.json()).compatible,true);server.close();});
test("assigns official, verified and community trust labels",async()=>{const {server,base,headers}=await fixture(),value=manifest(`com.example.trust-${crypto.randomUUID()}`);let response=await fetch(`${base}/api/v1/developer/plugins/${value.id}/versions`,{method:"POST",headers,body:JSON.stringify(upload(value))});const version=await response.json(),admin={"content-type":"application/json",authorization:"Bearer test-admin-token"};await fetch(`${base}/api/v1/admin/versions/${version.id}/review`,{method:"POST",headers:admin,body:JSON.stringify({decision:"approved"})});await fetch(`${base}/api/v1/admin/versions/${version.id}/publish`,{method:"POST",headers:admin});response=await fetch(`${base}/api/v1/admin/plugins/${value.id}/trust`,{method:"PUT",headers:admin,body:JSON.stringify({trustLevel:"official"})});assert.equal((await response.json()).trustLevel,"official");response=await fetch(`${base}/api/v1/plugins?q=${encodeURIComponent(value.id)}`);assert.equal((await response.json()).items[0].trustLevel,"official");server.close();});
test("supports search, update checks, ratings and abuse reports",async()=>{const {server,base,headers}=await fixture(),value=manifest(`com.example.market-${crypto.randomUUID()}`);let response=await fetch(`${base}/api/v1/developer/plugins/${value.id}/versions`,{method:"POST",headers,body:JSON.stringify(upload(value))});const version=await response.json(),admin={"content-type":"application/json",authorization:"Bearer test-admin-token"};await fetch(`${base}/api/v1/admin/versions/${version.id}/review`,{method:"POST",headers:admin,body:JSON.stringify({decision:"approved"})});await fetch(`${base}/api/v1/admin/versions/${version.id}/publish`,{method:"POST",headers:admin});response=await fetch(`${base}/api/v1/plugins?q=${encodeURIComponent(value.id)}`);assert.equal((await response.json()).items.length,1);response=await fetch(`${base}/api/v1/plugins/${value.id}/updates?currentVersion=0.1.0&hostVersion=0.6.0`);assert.equal((await response.json()).updateAvailable,true);response=await fetch(`${base}/api/v1/plugins/${value.id}/ratings`,{method:"POST",headers:{"content-type":"application/json","x-client-id":"rating-user"},body:JSON.stringify({score:5,comment:"Great"})});assert.equal(response.status,201);response=await fetch(`${base}/api/v1/plugins/${value.id}/reports`,{method:"POST",headers:{"content-type":"application/json","x-client-id":"report-user"},body:JSON.stringify({reason:"suspicious",details:"Review this plugin"})});const report=await response.json();response=await fetch(`${base}/api/v1/admin/reports`,{headers:admin});assert.equal((await response.json()).items.length,1);response=await fetch(`${base}/api/v1/admin/reports/${report.id}/resolve`,{method:"POST",headers:admin,body:JSON.stringify({status:"resolved",note:"Handled"})});assert.equal((await response.json()).status,"resolved");server.close();});
test("uploads, scans, publishes and downloads the real package bytes",async()=>{const project=resolve("../RToolsPluginSDK/fixtures/valid/hello-wasm"),cli=resolve("../RToolsPluginSDK/src/cli.js"),packed=spawnSync(process.execPath,[cli,"pack",project],{encoding:"utf8"});assert.equal(packed.status,0,packed.stderr);const bytes=await readFile(resolve(project,".rtools-dist/com.example.hello-wasm-1.0.0.rtools")),digest=createHash("sha256").update(bytes).digest("hex"),{server,base,headers}=await fixture();let response=await fetch(`${base}/api/v1/developer/plugins/com.example.hello-wasm/versions/1.0.0/package`,{method:"PUT",headers:{authorization:headers.authorization,"content-type":"application/vnd.rtools.plugin","x-package-sha256":digest},body:bytes});assert.equal(response.status,201);const version=await response.json();assert.equal(version.status,"pending_review");const admin={"content-type":"application/json",authorization:"Bearer test-admin-token"};await fetch(`${base}/api/v1/admin/versions/${version.id}/review`,{method:"POST",headers:admin,body:JSON.stringify({decision:"approved"})});await fetch(`${base}/api/v1/admin/versions/${version.id}/publish`,{method:"POST",headers:admin});response=await fetch(`${base}/api/v1/plugins/com.example.hello-wasm/versions/1.0.0/download`);assert.equal(response.status,200);assert.ok(response.headers.get("x-market-signature"));assert.equal(createHash("sha256").update(Buffer.from(await response.arrayBuffer())).digest("hex"),digest);server.close();});
