import mysql from "mysql2/promise";
import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import { scan } from "./store.js";

const hash=value=>createHash("sha256").update(value).digest("hex");
const duplicate=error=>error?.code==="ER_DUP_ENTRY";

export class MySqlStore {
  constructor(url) { this.pool=mysql.createPool({uri:url,connectionLimit:10,waitForConnections:true,queueLimit:100,charset:"utf8mb4"}); }
  async health() { await this.pool.query("SELECT 1"); return true; }
  async register({email,displayName}) {
    const connection=await this.pool.getConnection();
    try { await connection.beginTransaction(); const id=randomUUID(),token=`rtm_${randomBytes(24).toString("base64url")}`;
      await connection.execute("INSERT INTO developers(id,display_name,email) VALUES(?,?,?)",[id,displayName,email]);
      await connection.execute("INSERT INTO api_tokens(id,developer_id,token_hash) VALUES(?,?,?)",[randomUUID(),id,hash(token)]);
      await this.log(id,"developer.register",id,{},connection); await connection.commit();
      return {developer:{id,email,displayName,status:"active"},token};
    } catch(error) { await connection.rollback(); if(duplicate(error))throw Object.assign(new Error("Email already registered"),{code:"EMAIL_EXISTS",status:409}); throw error; } finally { connection.release(); }
  }
  async authenticate(token) {
    if(!token?.startsWith("rtm_"))return null;
    const [rows]=await this.pool.execute("SELECT d.id,d.email,d.display_name AS displayName,d.status FROM api_tokens t JOIN developers d ON d.id=t.developer_id WHERE t.token_hash=? AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at>NOW(3)) LIMIT 1",[hash(token)]);
    if(!rows[0]||rows[0].status!=="active")return null;
    await this.pool.execute("UPDATE api_tokens SET last_used_at=NOW(3) WHERE token_hash=?",[hash(token)]); return rows[0];
  }
  async createPlugin(owner,manifest) {
    const [rows]=await this.pool.execute("SELECT owner_id AS ownerId FROM plugins WHERE id=?",[manifest.id]);
    if(rows[0]&&rows[0].ownerId!==owner.id)throw Object.assign(new Error("Plugin ID is owned by another developer"),{code:"PLUGIN_OWNERSHIP_DENIED",status:403});
    await this.pool.execute("INSERT INTO plugins(id,owner_id,name,description,screenshots_json,license) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),screenshots_json=VALUES(screenshots_json),license=VALUES(license)",[manifest.id,owner.id,manifest.name,manifest.description||"",JSON.stringify(manifest.screenshots||[]),manifest.license||null]);
    await this.log(owner.id,rows[0]?"plugin.update":"plugin.create",manifest.id,{}); return {id:manifest.id,ownerId:owner.id,name:manifest.name,description:manifest.description||"",status:rows[0]?.status||"draft"};
  }
  async submitVersion(owner,manifest,input) {
    const [plugins]=await this.pool.execute("SELECT owner_id AS ownerId FROM plugins WHERE id=?",[manifest.id]);
    if(!plugins[0]||plugins[0].ownerId!==owner.id)throw Object.assign(new Error("Plugin ownership required"),{code:"PLUGIN_OWNERSHIP_DENIED",status:403});
    const id=randomUUID();
    try { await this.pool.execute("INSERT INTO plugin_versions(id,plugin_id,version,schema_version,min_host_version,max_host_version,entry_type,package_url,package_sha256,package_size,developer_signature,permissions_json,file_manifest_json,manifest_json,platforms_json,architectures_json,changelog) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,manifest.id,manifest.version,manifest.schemaVersion,manifest.rtools.minVersion,manifest.rtools.maxVersion||null,manifest.entry.type,input.objectKey||null,input.packageSha256,input.packageSize,input.developerSignature?JSON.stringify(input.developerSignature):null,JSON.stringify(manifest.permissions||[]),JSON.stringify(input.fileManifest||[]),JSON.stringify(manifest),JSON.stringify(manifest.platforms||["windows","macos","linux"]),JSON.stringify(manifest.architectures||["x86_64","aarch64"]),manifest.changelog||""]); }
    catch(error){if(duplicate(error))throw Object.assign(new Error("Version already exists"),{code:"PLUGIN_VERSION_EXISTS",status:409});throw error;}
    await this.log(owner.id,"version.submit",`${manifest.id}@${manifest.version}`,{packageSha256:input.packageSha256});
    return {id,pluginId:manifest.id,version:manifest.version,manifest,packageSha256:input.packageSha256,packageSize:input.packageSize,fileManifest:input.fileManifest||[],developerSignature:input.developerSignature||null,objectKey:input.objectKey||null,status:"pending_scan"};
  }
  async listPlugins(owner) {
    const [plugins]=await this.pool.execute("SELECT id,owner_id AS ownerId,name,description,status,created_at AS createdAt,updated_at AS updatedAt FROM plugins WHERE owner_id=? ORDER BY updated_at DESC",[owner.id]);
    for(const plugin of plugins){const [versions]=await this.pool.execute("SELECT id,plugin_id AS pluginId,version,package_sha256 AS packageSha256,package_size AS packageSize,review_status AS status,created_at AS createdAt FROM plugin_versions WHERE plugin_id=? ORDER BY created_at DESC",[plugin.id]);plugin.versions=versions;} return plugins;
  }
  async versionById(id) { const [rows]=await this.pool.execute("SELECT id,plugin_id AS pluginId,version,manifest_json AS manifest,package_sha256 AS packageSha256,package_size AS packageSize,developer_signature AS developerSignature,file_manifest_json AS fileManifest,review_status AS status,published_at AS publishedAt FROM plugin_versions WHERE id=?",[id]); const value=rows[0]; if(!value)throw Object.assign(new Error("Version not found"),{code:"PLUGIN_VERSION_NOT_FOUND",status:404}); for(const key of ["manifest","fileManifest"])if(typeof value[key]==="string")value[key]=JSON.parse(value[key]); return value; }
  async scanVersion(actor,versionId) { const version=await this.versionById(versionId),report=scan(version),status=report.errors.length?"scan_failed":"pending_review"; await this.pool.execute("UPDATE plugin_versions SET review_status=? WHERE id=?",[status,versionId]); await this.pool.execute("INSERT INTO reviews(id,plugin_version_id,status,automated_report_json) VALUES(?,?,?,?)",[randomUUID(),versionId,status,JSON.stringify(report)]); await this.log(actor.id,"version.scan",`${version.pluginId}@${version.version}`,report); return {...version,status,scanReport:report}; }
  async reviewVersion(actor,versionId,decision,note="") { const version=await this.versionById(versionId); if(!["pending_review","rejected"].includes(version.status))throw Object.assign(new Error("Version is not reviewable"),{code:"PLUGIN_STATE_INVALID",status:409}); await this.pool.execute("UPDATE plugin_versions SET review_status=? WHERE id=?",[decision,versionId]); await this.pool.execute("INSERT INTO reviews(id,plugin_version_id,status,reviewer_id,review_note) VALUES(?,?,?,?,?)",[randomUUID(),versionId,decision,actor.id,note]); await this.log(actor.id,`version.${decision}`,`${version.pluginId}@${version.version}`,{note}); return {...version,status:decision}; }
  async publishVersion(actor,versionId,publish=true) { const version=await this.versionById(versionId); if(publish&&version.status!=="approved"||!publish&&version.status!=="published")throw Object.assign(new Error("Version state does not allow this operation"),{code:"PLUGIN_STATE_INVALID",status:409}); const status=publish?"published":"unpublished"; await this.pool.execute("UPDATE plugin_versions SET review_status=?,published_at=? WHERE id=?",[status,publish?new Date():null,versionId]); await this.pool.execute("UPDATE plugins SET status=? WHERE id=?",[publish?"published":"draft",version.pluginId]); await this.log(actor.id,publish?"version.publish":"version.unpublish",`${version.pluginId}@${version.version}`,{}); return {...version,status,publishedAt:publish?new Date().toISOString():null}; }
  async catalog({query="",category="",tag=""}={}) { let sql="SELECT DISTINCT p.id,p.name,p.summary,p.description,p.icon_url AS iconUrl,p.homepage,p.repository,p.license,p.screenshots_json AS screenshots,p.trust_level AS trustLevel,p.updated_at AS updatedAt,COALESCE(AVG(r.score),0) AS ratingAverage,COUNT(DISTINCT r.id) AS ratingCount FROM plugins p LEFT JOIN ratings r ON r.plugin_id=p.id AND r.status='visible' LEFT JOIN plugin_categories pc ON pc.plugin_id=p.id LEFT JOIN plugin_tags pt ON pt.plugin_id=p.id WHERE p.status='published'",params=[];if(query){sql+=" AND (p.id LIKE ? OR p.name LIKE ? OR p.description LIKE ?)";params.push(`%${query}%`,`%${query}%`,`%${query}%`);}if(category){sql+=" AND pc.category_id=?";params.push(category);}if(tag){sql+=" AND pt.tag_id=?";params.push(tag);}sql+=" GROUP BY p.id ORDER BY p.updated_at DESC LIMIT 100";const [plugins]=await this.pool.execute(sql,params);for(const plugin of plugins){const [versions]=await this.pool.execute("SELECT id,version,min_host_version AS minHostVersion,max_host_version AS maxHostVersion,entry_type AS entryType,package_sha256 AS packageSha256,package_size AS packageSize,permissions_json AS permissions,platforms_json AS platforms,architectures_json AS architectures,download_count AS downloadCount,changelog,published_at AS publishedAt FROM plugin_versions WHERE plugin_id=? AND review_status='published' ORDER BY published_at DESC",[plugin.id]);plugin.versions=versions;}return plugins; }
  async download(pluginId,version) { const [rows]=await this.pool.execute("SELECT id,plugin_id AS pluginId,version,package_url AS objectKey,package_sha256 AS packageSha256,package_size AS packageSize,market_signature AS marketSignature FROM plugin_versions WHERE plugin_id=? AND version=? AND review_status='published'",[pluginId,version]);if(!rows[0])throw Object.assign(new Error("Published version not found"),{code:"PLUGIN_VERSION_NOT_FOUND",status:404});return rows[0]; }
  async setMarketSignature(actor,versionId,signature) { await this.pool.execute("UPDATE plugin_versions SET market_signature=? WHERE id=?",[JSON.stringify(signature),versionId]);const version=await this.versionById(versionId);await this.log(actor.id,"version.market-sign",`${version.pluginId}@${version.version}`,{});return {...version,marketSignature:signature}; }
  async auditLogs() { const [rows]=await this.pool.query("SELECT id,actor_id AS actorId,action,target,details,created_at AS createdAt FROM audit_logs ORDER BY id DESC LIMIT 500"); return rows; }
  async reviewQueue() { const [rows]=await this.pool.query("SELECT v.id,v.plugin_id AS pluginId,p.name AS pluginName,v.version,v.entry_type AS entryType,v.package_sha256 AS packageSha256,v.package_size AS packageSize,v.permissions_json AS permissions,v.review_status AS status,v.created_at AS createdAt,(SELECT r.automated_report_json FROM reviews r WHERE r.plugin_version_id=v.id AND r.automated_report_json IS NOT NULL ORDER BY r.created_at DESC LIMIT 1) AS scanReport FROM plugin_versions v JOIN plugins p ON p.id=v.plugin_id ORDER BY v.created_at DESC LIMIT 500"); return rows; }
  async listDevelopers() { const [rows]=await this.pool.query("SELECT d.id,d.display_name AS displayName,d.email,d.status,d.created_at AS createdAt,d.updated_at AS updatedAt,COUNT(DISTINCT p.id) AS pluginCount,COUNT(DISTINCT CASE WHEN t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at>NOW(3)) THEN t.id END) AS activeTokenCount FROM developers d LEFT JOIN plugins p ON p.owner_id=d.id LEFT JOIN api_tokens t ON t.developer_id=d.id GROUP BY d.id ORDER BY d.created_at DESC LIMIT 500"); return rows; }
  async setDeveloperStatus(actor,id,status) { const connection=await this.pool.getConnection();try{await connection.beginTransaction();const [result]=await connection.execute("UPDATE developers SET status=? WHERE id=?",[status,id]);if(!result.affectedRows)throw Object.assign(new Error("Developer not found"),{code:"DEVELOPER_NOT_FOUND",status:404});if(status==="suspended"){await connection.execute("UPDATE plugin_versions v JOIN plugins p ON p.id=v.plugin_id SET v.review_status='unpublished' WHERE p.owner_id=? AND v.review_status='published'",[id]);await connection.execute("UPDATE plugins SET status='suspended' WHERE owner_id=?",[id]);}await this.log(actor.id,"developer.status",id,{status},connection);await connection.commit();const [rows]=await this.pool.execute("SELECT id,display_name AS displayName,email,status FROM developers WHERE id=?",[id]);return rows[0];}catch(error){await connection.rollback();throw error;}finally{connection.release();} }
  async revokeDeveloperTokens(actor,id) { const [exists]=await this.pool.execute("SELECT id FROM developers WHERE id=?",[id]); if(!exists[0])throw Object.assign(new Error("Developer not found"),{code:"DEVELOPER_NOT_FOUND",status:404}); const [result]=await this.pool.execute("UPDATE api_tokens SET revoked_at=NOW(3) WHERE developer_id=? AND revoked_at IS NULL",[id]); await this.log(actor.id,"developer.tokens.revoke",id,{revoked:result.affectedRows}); return {revoked:result.affectedRows}; }
  async createToken(owner,name){const id=randomUUID(),token=`rtm_${randomBytes(24).toString("base64url")}`;await this.pool.execute("INSERT INTO api_tokens(id,developer_id,token_hash,name) VALUES(?,?,?,?)",[id,owner.id,hash(token),name]);await this.log(owner.id,"token.create",id,{name});return {id,token,name};}
  async listTokens(owner){const [rows]=await this.pool.execute("SELECT id,name,last_used_at AS lastUsedAt,expires_at AS expiresAt,revoked_at AS revokedAt,created_at AS createdAt FROM api_tokens WHERE developer_id=? ORDER BY created_at DESC",[owner.id]);return rows;}
  async revokeToken(owner,id){const [result]=await this.pool.execute("UPDATE api_tokens SET revoked_at=NOW(3) WHERE id=? AND developer_id=? AND revoked_at IS NULL",[id,owner.id]);if(!result.affectedRows)throw Object.assign(new Error("Token not found"),{code:"TOKEN_NOT_FOUND",status:404});await this.log(owner.id,"token.revoke",id,{});return {revoked:true};}
  async incrementDownload(pluginId,version){await this.pool.execute("UPDATE plugin_versions SET download_count=download_count+1 WHERE plugin_id=? AND version=? AND review_status='published'",[pluginId,version]);}
  async ratePlugin(pluginId,userKey,score,comment){try{await this.pool.execute("INSERT INTO ratings(id,plugin_id,user_key,score,comment) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE score=VALUES(score),comment=VALUES(comment)",[randomUUID(),pluginId,userKey,score,comment]);}catch(error){if(error.code==="ER_NO_REFERENCED_ROW_2")throw Object.assign(new Error("Plugin not found"),{code:"PLUGIN_NOT_FOUND",status:404});throw error;}return {ok:true};}
  async pluginRatings(pluginId){const [rows]=await this.pool.execute("SELECT id,score,comment,created_at AS createdAt,updated_at AS updatedAt FROM ratings WHERE plugin_id=? AND status='visible' ORDER BY updated_at DESC LIMIT 100",[pluginId]);return rows;}
  async reportPlugin(pluginId,userKey,input){const id=randomUUID();try{await this.pool.execute("INSERT INTO reports(id,plugin_id,version,reporter_key,reason,details) VALUES(?,?,?,?,?,?)",[id,pluginId,input.version||null,userKey,input.reason,input.details||""]);}catch(error){if(error.code==="ER_NO_REFERENCED_ROW_2")throw Object.assign(new Error("Plugin not found"),{code:"PLUGIN_NOT_FOUND",status:404});throw error;}return {id,pluginId,status:"open"};}
  async listReports(){const [rows]=await this.pool.query("SELECT id,plugin_id AS pluginId,version,reason,details,status,resolution_note AS resolutionNote,created_at AS createdAt,updated_at AS updatedAt FROM reports ORDER BY created_at DESC LIMIT 500");return rows;}
  async resolveReport(actor,id,status,note){const [result]=await this.pool.execute("UPDATE reports SET status=?,resolution_note=? WHERE id=?",[status,note,id]);if(!result.affectedRows)throw Object.assign(new Error("Report not found"),{code:"REPORT_NOT_FOUND",status:404});await this.log(actor.id,"report.resolve",id,{status});return {id,status,resolutionNote:note};}
  async suspendPlugin(actor,id){const [result]=await this.pool.execute("UPDATE plugins SET status='suspended' WHERE id=?",[id]);if(!result.affectedRows)throw Object.assign(new Error("Plugin not found"),{code:"PLUGIN_NOT_FOUND",status:404});await this.pool.execute("UPDATE plugin_versions SET review_status='unpublished' WHERE plugin_id=? AND review_status='published'",[id]);await this.log(actor.id,"plugin.suspend",id,{});return {id,status:"suspended"};}
  async categories(){const [rows]=await this.pool.query("SELECT id,name,description,sort_order AS sortOrder FROM categories ORDER BY sort_order,name");return rows;}
  async tags(){const [rows]=await this.pool.query("SELECT id,name FROM tags ORDER BY name LIMIT 200");return rows;}
  async setTaxonomy(actor,id,{categories=[],tags=[]}){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const [exists]=await connection.execute("SELECT id FROM plugins WHERE id=?",[id]);if(!exists[0])throw Object.assign(new Error("Plugin not found"),{code:"PLUGIN_NOT_FOUND",status:404});await connection.execute("DELETE FROM plugin_categories WHERE plugin_id=?",[id]);await connection.execute("DELETE FROM plugin_tags WHERE plugin_id=?",[id]);for(const category of categories)await connection.execute("INSERT INTO plugin_categories(plugin_id,category_id) VALUES(?,?)",[id,category]);for(const tag of tags){const normalized=String(tag).trim().toLowerCase().slice(0,64);if(!normalized)continue;await connection.execute("INSERT IGNORE INTO tags(id,name) VALUES(?,?)",[normalized,normalized]);await connection.execute("INSERT INTO plugin_tags(plugin_id,tag_id) VALUES(?,?)",[id,normalized]);}await this.log(actor.id,"plugin.taxonomy",id,{categories,tags},connection);await connection.commit();return {id,categories,tags};}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  async setTrustLevel(actor,id,trustLevel){const [result]=await this.pool.execute("UPDATE plugins SET trust_level=? WHERE id=?",[trustLevel,id]);if(!result.affectedRows)throw Object.assign(new Error("Plugin not found"),{code:"PLUGIN_NOT_FOUND",status:404});await this.log(actor.id,"plugin.trust",id,{trustLevel});return {id,trustLevel};}
  async ensureAdmin(username,password){const [rows]=await this.pool.execute("SELECT id FROM admin_users WHERE username=?",[username]);if(rows[0])return;const salt=randomBytes(16).toString("hex"),digest=scryptSync(password,salt,32).toString("hex");await this.pool.execute("INSERT INTO admin_users(id,username,password_hash,role) VALUES(?,?,?,'super_admin')",[randomUUID(),username,`${salt}:${digest}`]);}
  async adminLogin(username,password){const [rows]=await this.pool.execute("SELECT id,username,password_hash AS passwordHash,role,status FROM admin_users WHERE username=?",[username]),admin=rows[0];if(!admin||admin.status!=="active")throw Object.assign(new Error("Invalid administrator credentials"),{code:"ADMIN_LOGIN_INVALID",status:401});const [salt,expected]=admin.passwordHash.split(":"),actual=scryptSync(password,salt,32);if(!timingSafeEqual(actual,Buffer.from(expected,"hex")))throw Object.assign(new Error("Invalid administrator credentials"),{code:"ADMIN_LOGIN_INVALID",status:401});const token=`rta_${randomBytes(24).toString("base64url")}`;await this.pool.execute("INSERT INTO admin_sessions(id,admin_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(3),INTERVAL 8 HOUR))",[randomUUID(),admin.id,hash(token)]);await this.log(admin.id,"admin.login",admin.id,{});return {token,expiresIn:28800,admin:{id:admin.id,username:admin.username,role:admin.role}};}
  async authenticateAdmin(token){if(!token?.startsWith("rta_"))return null;const [rows]=await this.pool.execute("SELECT a.id,a.username,a.role FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>NOW(3) AND a.status='active'",[hash(token)]);return rows[0]||null;}
  async log(actorId,action,target,details,connection=this.pool) { await connection.execute("INSERT INTO audit_logs(actor_id,action,target,details) VALUES(?,?,?,?)",[actorId,action,target,JSON.stringify(details)]); }
}
